dotfiles:
    symlink:
        .sbclrc:
    packages:
        - alacritty-git
        - alacritty-terminfo-git
        - arandr
        - bluejeans
        - borg
        - docker
        - firefox
        - flashplugin
        - fwupd
        - fzf
        - hub
        - i3blocks
        - i3-gaps
        - i3lock-fancy-git
        - ifenslave
        - irssi
        - isync
        - jq
        - light
        - msmtp
        - multimc-git
        - neomutt
        - neovim
        - neovim-remote
        - nerd-fonts-fantasque-sans-mono
        - nerd-fonts-hack
        - netlify
        - nitrogen
        - notmuch
        - notmuch-mutt
        - openscad
        - osbuddy
        - otf-fantasque-sans-mono
        - otf-font-awesome
        - pass-clip
        - pavucontrol
        - pdk
        - picard
        - rbenv
        - rofi
        - roswell
        - ruby-build
        - rustup
        - sbcl
        - scrot
        - shellcheck
        - slack-desktop
        - spotify
        - teensy-loader-cli
        - terminus-font
        - ttf-fantasque-sans-mono
        - ttf-font-awesome
        - urlview
        - vinagre
        - vivaldi
        - xautolock
        - xbindkeys
        - yarn
