#!/usr/bin/env python

import string
import random
import sys

def gen_pw(length):
    print "".join(map(lambda r: random.choice(string.ascii_letters + string.digits + "_-$%&#!"), range(0, length)))

if __name__ == '__main__':
    gen_pw(int(sys.argv[1]))
