#!/bin/sh
tmux start-server
tmux -L hack attach-session -d -t hack || {
  tmux -L hack new-session -d -s hack
  tmux -L hack new-window -n IRC "ssh ishamael.sharpe.id.au"
  tmux -L hack swap-window -s 1 -t 2
  tmux -L hack attach-session -d -t hack
}
