#!/usr/bin/env ruby

require 'optparse'

class SpotifyCtl
  def self.run
    OptionParser.new do |opts|
      opts.banner = "Usage: spotifyctl [options]"

      opts.on('-p', '--playpause', 'Toggle play/pause') do
        Spotify.playpause if Spotify.running?
      end

      opts.on('-n', '--next', 'Play the next track') do
        Spotify.next_track if Spotify.running?
      end

      opts.on('-v', '--previous', 'Play the previous track') do
        Spotify.previous_track if Spotify.running?
      end

      opts.on('-c', '--current', 'Display current track info') do
        if Spotify.running?
          current = Spotify.current_track
          puts " #{current[:artist]} - #{current[:name]} "
        end
      end
    end.parse!
  end

  class Spotify
    def self.running?
      running = osascript <<-END
        tell application "System Events"
          (name of processes) contains "Spotify"
        end tell
      END

      running.strip == 'true'
    end

    def self.next_track
      osascript 'tell application "Spotify" to next track'
    end

    def self.previous_track
      osascript 'tell application "Spotify" to previous track'
    end

    def self.playpause
      osascript 'tell application "Spotify" to playpause'
    end

    def self.current_track
      artist = osascript <<-END
        tell application "Spotify"
          get artist of current track
        end tell
      END
      name = osascript <<-END
        tell application "Spotify"
          get name of current track
        end tell
      END
      {:name => name.strip, :artist => artist.strip}
    end

    private
    def self.osascript(script)
      args = script.split("\n").map { |line| ['-e', "'#{line.strip}'"] }.flatten
      `osascript #{args.join(' ')}`
    end
  end
end

SpotifyCtl.run
