#!/bin/sh

LOCKFILE=~/.sync-mail.lock
[ -f $LOCKFILE ] && exit 0
trap "{ rm -f $LOCKFILE ; exit 0; }" EXIT
echo "$$" > $LOCKFILE

/sbin/ping -c 1 imap.gmail.com >/dev/null 2>&1 || exit 0
/opt/boxen/homebrew/bin/offlineimap > /dev/null 2>&1
