#!/usr/bin/env ruby

class Tmux
  class Battery
    SYMBOLS = {
      :charging    => ["21c8".hex].pack("U*"),
      :discharging => ["21ca".hex].pack("U*"),
    }

    def initialize
      @output = `pmset -g batt`.strip.split("\n")
      parse!
    end

    def run
      case @state
      when :charging
        puts " #{@time} #{SYMBOLS[:charging]} "
      when :discharging
        puts " #{@time} #{SYMBOLS[:discharging]} "
      end
    end
  private
    def parse!
      if @output.first.include? 'AC Power'
        @source = :ac
      else
        @source = :battery
      end

      data = @output.last.strip.squeeze(' ').split(' ')

      @percert = data[1][0..-3]
      @state = data[2][0..-2].to_sym
      @time = data[3] == '(no' ? '...' : data[3]
    end
  end
end

Tmux::Battery.new.run
