#!/bin/bash

script/bootstrap

pushd puppet > /dev/null
bundle check > /dev/null || bundle install --path vendor/gems --binstubs
sudo bin/puppet apply --modulepath=modules manifests/workstation.pp
popd > /dev/null
