#!/bin/bash

function ensure_package() {
    local package="$1"

    pacman -Qe "${package}" > /dev/null
    if [[ $? -ne 0 ]]; then
        sudo pacman -S --noconfirm "${package}"
    fi
}

ensure_package "augeas"
ensure_package "ruby-bundler"

pushd puppet > /dev/null
bundle check > /dev/null || bundle install --path vendor/gems --binstubs
popd > /dev/null
